config/routes.rb
HowTo::Application.routes.draw do
  root :to => "instructions#index"

  resources :instructions do
    resources :tasks
  end

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :tasks, :dependent => :delete_all
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :instruction
  attr_accessible :task

  validates :task, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  # GET /instructions
  # GET /instructions.json
  def index
    @instructions = Instruction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instructions }
    end
  end

  # GET /instructions/1
  # GET /instructions/1.json
  def show
    @instruction = Instruction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instruction }
    end
  end

  # GET /instructions/new
  # GET /instructions/new.json
  def new
    @instruction = Instruction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instruction }
    end
  end

  # GET /instructions/1/edit
  def edit
    @instruction = Instruction.find(params[:id])
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @instruction = Instruction.new(params[:instruction])

    respond_to do |format|
      if @instruction.save
        format.html { redirect_to @instruction, notice: 'Instruction was successfully created.' }
        format.json { render json: @instruction, status: :created, location: @instruction }
      else
        format.html { render action: "new" }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

   def update
    @instruction = Instruction.find(params[:id])

    respond_to do |format|
      if @instruction.update_attributes(params[:instruction])
        format.html { redirect_to @instruction, notice: 'Instruction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    @instruction = Instruction.find(params[:id])
    @instruction.destroy

    respond_to do |format|
      format.html { redirect_to instructions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_instruction
  before_filter :find_task, :only => [:show, :edit, :update, :destroy]
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end


  def show
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = @instruction.tasks.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @instruction.tasks.build(params[:task])
    if @task.save
      flash[:notice] = "Task has been created."
      redirect_to [@instruction]
    else
      flash[:alert] = "Task has not been created."
      render :action => "new"
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    if @task.update_attributes(params[:task])
      flash[:notice] = "Task has been updated."
      redirect_to [@instruction, @task]
    else
      flash[:alert] = "Task has not been updated."
      render :action => "edit"
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    flash[:notice] = "Task has been deleted."
    redirect_to @instruction
  end

  private
    def find_instruction
      @instruction = Instruction.find(params[:instruction_id])
    end
    def find_task
      @task = @instruction.tasks.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/instructions/_form.html.erb
<%= form_for(@instruction) do |f| %>
  <% if @instruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
      <% @instruction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructions/edit.html.erb
<h2>Editing instruction</h2>

<%= render 'form' %>

<%= link_to 'Show', @instruction %> |
<%= link_to 'Back', instructions_path %>

app/views/instructions/index.html.erb
<h2>Instructions</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instructions.each do |instruction| %>
  <tr>
    <td><%= link_to instruction.name, instruction %></td>
    <td><%= instruction.description %></td>
    <td><%= link_to 'Show', instruction %></td>
    <td><%= link_to 'Edit', edit_instruction_path(instruction) %></td>
    <td><%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instruction', new_instruction_path %>

app/views/instructions/new.html.erb
<h1>New instruction</h1>

<%= render 'form' %>

<%= link_to 'Back', instructions_path %>

app/views/instructions/show.html.erb
<p>
  <b>Name:</b>
  <%= @instruction.name %>
</p>

<p>
  <b>Description:</b>
  <%= @instruction.description %>
</p>

<ul id='tasks'>
  <% @instruction.tasks.each do |task| %>
    <li>
      <%= link_to task.task, [@instruction, task] %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Task', new_instruction_task_path(@instruction) %> <br>
<%= link_to 'Edit Instructions', edit_instruction_path(@instruction) %> |
<%= link_to 'Delete Instructions', instruction_path(@instruction),
    :method => :delete, :confirm => "Are you sure you want to delete this instruction?" %>
<%= link_to 'Back', instructions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>How To: An Instructables Knock Off | By Steph Datu</title>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="topbar">
  <div class="fill">
    <div class="container">
      <a class="brand" href="/">Instructions Lists App</a>
      <ul class="nav">
        <li class="active"><a href="/instructions">Instruction Lists</a></li>
        <li ><%= link_to 'New Instruction List', new_instruction_path %></li>
      </ul>
    </div>
  </div>
</div>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>


<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    By Stephanie Datu | Layout by Rails Girls 2013
  </div>
</footer>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for [@instruction, @task] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h2>Editing a task in <%= @instruction.name %></h2>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', instruction_tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Task</th>
    <th>Instruction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.task %></td>
    <td><%= task.instruction %></td>
    <td><%= link_to 'Show', instruction_task_path %></td>
    <td><%= link_to 'Edit', edit_instruction_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_instruction_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', instruction_tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @task.task %>
</p>


<%= link_to 'Edit Task', edit_instruction_task_path %> |
<%= link_to "Delete Task", [@instruction, @task], :method => :delete,
    :confirm => "Are you sure you want to delete this task?" %> |
<%= link_to 'Back', instruction_tasks_path %>